platform :ios, '12.0'

target 'ExampleAppUIKit' do
    use_frameworks!

    pod 'TrustlySDK', :path => '../..'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
    end
  end
end