# This workflow ensures that pull requests and commits to the main iOS branches are properly analyzed and tested.
# Workflow 'iOS Main Branches Quality Check' runs static code analysis, installs dependencies, and verifies code coverage.
# It helps maintain code quality and adherence to best practices before merging into the main branch.
# For furthuer information, check: https://trustly.atlassian.net/wiki/spaces/Engineering/pages/71335182337/iOS+Main+Branches+Quality+Check
name: iOS Main Branches Quality Check

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  SONAR_HOST_URL: "https://sonarqube.trustly.one"
  SONAR_PROJECT_KEY: "trustly-ios"
  SONAR_PROJECT_NAME: "trustly-ios"
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SECRET }}

jobs:
  run_tests_and_sonar_analysis:
    runs-on: macOS-latest
    if: >-
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'DEV'

    steps:
      # actions/checkout -> v6.0.2
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      # maxim-lobanov/setup-xcode -> v1.7.0
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: latest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler: 'latest'
          bundler-cache: true

      - name: Install sonar-scanner
        run: brew install sonar-scanner

      - name: Reset SonarScanner cache
        run: |
          rm -rf ~/.sonar/cache
          mkdir -p "${RUNNER_TEMP}/.sonar"
