name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GIT_TOKEN_SECRET }}
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.number }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SECRET }}
  SONAR_HOST_URL: "https://sonarqube.trustly.one"
  SONAR_PROJECT_KEY: "trustly-ios"
  SONAR_PROJECT_NAME: "trustly-ios"

jobs:
  SonarQube:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install --project-directory=Example

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and Test with Code Coverage
        run: |
          xcodebuild \
            -workspace Example/TrustlySDK.xcworkspace \
            -scheme TrustlySDK-Example \
            -derivedDataPath Build/ \
            -enableCodeCoverage YES \
            test \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    
      - name: Generate SonarQube Coverage Report
        run: |
          bash xccov-to-sonarqube-generic.sh Build/Logs/Test/Run-swift-coverage-example-$(date +"%Y.%m.%d_%H-%M-%S-%z").xcresult/ > Coverage.xml

      - name: Install sonar-scanner
        run: |
          brew install sonar-scanner

      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
                -Dsonar.host.url=${SONAR_HOST_URL} \
                -Dsonar.login=${SONAR_TOKEN} \
                -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                -Dsonar.projectName=${SONAR_PROJECT_NAME} \
                -Dsonar.pullrequest.base="${{ github.base_ref }}" \
                -Dsonar.pullrequest.branch="${{ github.head_ref }}" \
                -Dsonar.pullrequest.key="${{ github.event.pull_request.number }}" \
                -Dsonar.scm.revision="${{ github.event.pull_request.head.sha }}" \
                -Dsonar.scm.disabled=true \
                -Dsonar.language=swift \
                -Dsonar.sources="." \
                -Dsonar.swift.coverage.reportPaths=coverage.report \
                -Dsonar.cfamily.compile-commands=compile_commands.json \
                -Dsonar.verbose=true